[package]
name = "steamworksjs"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = "2.1.0"
napi-derive = "2.1.0"
steamworks = { git = "https://github.com/ceifa/steamworks-rs.git" }

[build-dependencies]
napi-build = "1.2.1"