name: Publish

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        arch: [ia32, x64]
        os: [windows-2022, ubuntu-20.04, macos-11]
        exclude:
          - os: macos-latest
            arch: ia32

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: 16.x

    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Build
      env:
        STEAM_SDK_LOCATION: sdk
      run: |
        npm i
        node tools/unzip-sdk ${{ secrets.SDK_PASSWORD }}
        npm run build

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.os }}
        path: dist

  deploy:
    runs-on: ubuntu-20.04
    needs: build
    strategy:
      matrix:
        os: [windows-2022, ubuntu-20.04, macos-11]

    steps:
    - uses: actions/checkout@v2

    - name: Download build
      uses: actions/download-artifact@v2
      with:
        name: ${{ matrix.os }}
        path: dist

    - name: Log files
      run: |
        echo "Root directory:" && ls
        echo "Dist directory:" && ls dist